apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "application.name" . }}
    version: "{{ .Values.image.tag }}"
    release: "{{ .Release.Name }}"
data:
{{ (.Files.Glob "config/*").AsConfig | indent 2 }}