{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "application.fullname" $ }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "application.fullname" . }}
    version: "{{ .Values.image.tag }}"
    release: "{{ .Release.Name }}"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1000m
spec:
  ingressClassName: {{ .Values.ingress.loadbalancer | quote }}
  rules:
    - host: {{ .Values.ingress.hosts }}
      http:
        paths:
          {{- range $key, $value  := .Values.ingress.locations}}
          - path: {{ $value.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $value.service }}
                port: 
                  number: {{ $value.port }}
          {{- end }}
{{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.hosts }}
    secretName: {{ .Values.ingress.secret }}
{{- end }}
{{- end }}