apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-ui
spec:
  capacity:
    storage: 1Gi
  claimRef: 
    name: redis-ui-config
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "default"
  hostPath:
    path: /home/redis-ui