{{- if .Values.persistence.pvc }}
{{- range $key, $value := .Values.persistence.pvc }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "application.fullname" $ }}-{{ $value.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "application.name" $ }}
    version: "{{ $.Values.image.tag }}"
    release: "{{ $.Release.Name }}"
spec:
  accessModes:
    - {{ $value.accessMode | quote }}
  resources:
    requests:
      storage: "{{ $value.size }}Gi"
  storageClassName: {{ $value.storageClass }}
{{- end }}
{{- end }}