apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-controller-0
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "default"
  hostPath:
    path: /home/kafka