apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-redis-master-0
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "default"
  hostPath:
    path: /home/redis/replica