apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-redis-replica-0
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "default"
  claimRef:
    name: redis-data-redis-replicas-0
    namespace: redis
  hostPath:
    path: /home/replicas