name: CI

on:
  push:
    tags:
      - '*'          # run on any tag push
    branches:
      - main
  pull_request:

jobs:
  trivy-scan:
    name: Download & Scan Terraform Providers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip curl

      - name: Download & prepare Vault provider v5.0.0
        run: |
          curl -sSL \
            https://releases.hashicorp.com/terraform-provider-vault/5.0.0/terraform-provider-vault_5.0.0_linux_amd64.zip \
            -o vault.zip
          mkdir -p vault
          unzip vault.zip -d vault
          chmod +x vault/terraform-provider-vault_5.0.0_linux_amd64

      - name: Scan Vault provider
        uses: aquasecurity/trivy-action@0.31.0
        with:
          scan-type: rootfs
          scan-target: vault/terraform-provider-vault_5.0.0_linux_amd64
          scanners: vuln
          severity: CRITICAL
          exit-code: '1'

      - name: Download & prepare Random provider v3.7.2
        run: |
          curl -sSL \
            https://releases.hashicorp.com/terraform-provider-random/3.7.2/terraform-provider-random_3.7.2_linux_amd64.zip \
            -o random.zip
          mkdir -p random
          unzip random.zip -d random
          chmod +x random/terraform-provider-random_3.7.2_linux_amd64

      - name: Scan Random provider
        uses: aquasecurity/trivy-action@0.31.0
        with:
          scan-type: rootfs
          scan-target: random/terraform-provider-random_3.7.2_linux_amd64
          scanners: vuln
          severity: CRITICAL
          exit-code: '1'
