name: CI

on:
  push:
    tags:
      - '*'        # run on any tag push
    branches:
      - main
  pull_request:

jobs:

  DownloadProviders:
    name: Download Terraform Provider Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Install unzip & curl
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip curl

      - name: Download Vault provider v5.0.0
        run: |
          curl -sSL \
            https://releases.hashicorp.com/terraform-provider-vault/5.0.0/terraform-provider-vault_5.0.0_linux_amd64.zip \
            -o vault.zip
          mkdir -p vault/terraform-provider-vault
          unzip vault.zip -d vault/terraform-provider-vault

      - name: Download Random provider v3.7.2
        run: |
          curl -sSL \
            https://releases.hashicorp.com/terraform-provider-random/3.7.2/terraform-provider-random_3.7.2_linux_amd64.zip \
            -o random.zip
          mkdir -p random/terraform-provider-random
          unzip random.zip -d random/terraform-provider-random

      - name: Upload Vault provider
        uses: actions/upload-artifact@v4
        with:
          name: terraform-provider-vault
          path: vault/terraform-provider-vault

      - name: Upload Random provider
        uses: actions/upload-artifact@v4
        with:
          name: terraform-provider-random
          path: random/terraform-provider-random

  ScanWithTrivy:
    name: Security Scan with Trivy
    runs-on: ubuntu-latest
    needs: DownloadProviders

    steps:
      - name: Download Vault provider
        uses: actions/download-artifact@v4
        with:
          name: terraform-provider-vault
          path: ./vault/terraform-provider-vault

      - name: Make Vault provider executable
        run: chmod +x vault/terraform-provider-vault/*

      - name: Scan Vault provider
        run: trivy rootfs --scanners vuln vault/terraform-provider-vault/*

      - name: Download Random provider
        uses: actions/download-artifact@v4
        with:
          name: terraform-provider-random
          path: ./random/terraform-provider-random

      - name: Make Random provider executable
        run: chmod +x random/terraform-provider-random/*

      - name: Scan Random provider
        run: trivy rootfs --scanners vuln random/terraform-provider-random/*
