name: CI

on:
  push:
    branches:
      - main

jobs:

  DownloadProviders:
    name: Download Terraform Provider Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Install unzip & curl
        run: sudo apt-get update && sudo apt-get install -y unzip curl

      - name: Download Vault provider v5.0.0
        run: |
          curl -sSL \
            https://releases.hashicorp.com/terraform-provider-vault/5.0.0/terraform-provider-vault_5.0.0_linux_amd64.zip \
            -o vault.zip
          unzip vault.zip -d vault
          mkdir -p vault/terraform-provider-vault
          mv vault/terraform-provider-vault_* vault/terraform-provider-vault

      - name: Download Random provider v3.7.2
        run: |
          curl -sSL \
            https://releases.hashicorp.com/terraform-provider-random/3.7.2/terraform-provider-random_3.7.2_linux_amd64.zip \
            -o random.zip
          unzip random.zip -d random
          mkdir -p random/terraform-provider-random
          mv random/terraform-provider-random_* random/terraform-provider-random

      - name: Upload Vault provider
        uses: actions/upload-artifact@v4
        with:
          name: terraform-provider-vault
          path: vault/terraform-provider-vault

      - name: Upload Random provider
        uses: actions/upload-artifact@v4
        with:
          name: terraform-provider-random
          path: random/terraform-provider-random

  ScanWithTrivy:
    name: Security Scan with Trivy
    runs-on: ubuntu-latest
    needs: DownloadProviders

    steps:
      - name: Download Vault provider artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-provider-vault
          path: ./vault/terraform-provider-vault

      - name: Download Random provider artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-provider-random
          path: ./random/terraform-provider-random

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run Trivy JSON scan against Vault provider
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: './vault/terraform-provider-vault'
          scanners: 'vuln'
          severity: 'CRITICAL,HIGH,MEDIUM'
          format: 'json'
          output: 'trivy-vault-report.json'
          exit-code: '1'

      - name: Show Vulnerability Count for Vault provider
        run: |
          COUNT=$(jq '[.Results[].Vulnerabilities[]] | length' trivy-vault-report.json)
          echo "Vault provider vulnerabilities (>= Medium): $COUNT"

      - name: Run Trivy JSON scan against Random provider
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: './random/terraform-provider-random'
          scanners: 'vuln'
          severity: 'CRITICAL,HIGH,MEDIUM'
          format: 'json'
          output: 'trivy-random-report.json'
          exit-code: '1'

      - name: Show Vulnerability Count for Random provider
        run: |
          COUNT=$(jq '[.Results[].Vulnerabilities[]] | length' trivy-random-report.json)
          echo "Random provider vulnerabilities (>= Medium): $COUNT"
