name: CI

on:
  push:
    tags:
      - '*'          # run on any tag push
    branches:
      - main
  pull_request:

jobs:
  trivy-scan:
    name: Download & Scan Terraform Providers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install prerequisites
        run: sudo apt-get update && sudo apt-get install -y unzip curl

      - id: vault
        name: Download & prepare Vault provider v5.0.0
        run: |
          curl -sSL \
            https://releases.hashicorp.com/terraform-provider-vault/5.0.0/terraform-provider-vault_5.0.0_linux_amd64.zip \
            -o vault.zip
          mkdir -p vault
          unzip vault.zip -d vault
          BIN=$(ls vault/terraform-provider-vault_*)
          chmod +x "$BIN"
          echo "provider_path=$BIN" >> $GITHUB_OUTPUT

      - name: Scan Vault provider
        uses: aquasecurity/trivy-action@0.31.0
        with:
          scan-type: rootfs
          scan-target: ${{ steps.vault.outputs.provider_path }}
          scanners: vuln
          severity: CRITICAL
          exit-code: '1'

      - id: random
        name: Download & prepare Random provider v3.7.2
        run: |
          curl -sSL \
            https://releases.hashicorp.com/terraform-provider-random/3.7.2/terraform-provider-random_3.7.2_linux_amd64.zip \
            -o random.zip
          mkdir -p random
          unzip random.zip -d random
          BIN=$(ls random/terraform-provider-random_*)
          chmod +x "$BIN"
          echo "provider_path=$BIN" >> $GITHUB_OUTPUT

      - name: Scan Random provider
        uses: aquasecurity/trivy-action@0.31.0
        with:
          scan-type: rootfs
          scan-target: ${{ steps.random.outputs.provider_path }}
          scanners: vuln
          severity: CRITICAL
          exit-code: '1'
